### ISSUE TITLE
`iohub convert` chunks by XY planes rather than XYZ volumes

### ISSUE THREAD

**Issue by ieivanov** [czbiohub-sf/iohub#176]
Was this an intentional decision? I see the docstring says that using XY planes is fastest at conversion time, but that doesn't align with the rest of our processing pipelines which chunk by XYZ volumes.

**Comment by ieivanov** [comment]
P.S. The mantis microscope generates a lot of small images - if we chunk by XY planes our storage will be littered with 500 kb files which cause problems during backup

**Comment by ziw-liu** [comment]
It was intentional. Since acquisition comes in arbitrary axis ordering and arrays can be larger than memory, writing chunks larger than a frame while also avoiding redundant serialization/deserialization will make the converter based on the current readers very complex. I planned to rewrite the converter once we have UAPI, and use Dask's `to_zarr` to handle this issue.

There is an API argument (`TIFFConverter(chunks=...)`) to pass in the exact chunk size to override this default behavior, possibly at the cost of conversion speed (when acquisition order is not CZYX). We can promote that to a CLI option if necessary.

**Comment by ieivanov** [comment]
Thanks.

As a first step, let's add a CLI option for specifying the chunk size as `XY` or `XYZ` so that we don't have to figure out the exact numbers; the default for now can be `XY`. 

We are now generating TB of data and I think it's important that we don't fill our storage with tiny files. We'll discuss a better solution in person

**Comment by ieivanov** [comment]
For example, `/hpc/projects/comp.micro/mantis/2023_08_09_HEK_PCNA_H2B/0-zarr/pcna_rac1_virtual_staining_pcna_redo_2/` alone has ~175000 files.

[Here](https://czbiohubsf.slack.com/archives/C01LY099TU2/p1683077942259069) `griznog` discussed the influence of large number of files on the filesystem. We need to stay in the mid/low 10M of files. This acquisition alone (which is not that big) accounts for ~1% of that target.

**Comment by mattersoflight** [comment]
During our previous discussion, we realized that XYZ chunking is optimal size for the majority of our pipelines.  `iohub` should provide that either via CLI or via API, whichever is simpler and more general. 

I totally see that if the underlying reader does not support lazy loading of XYZ data in memory, chunking along XY is a safe bet. But, we can throw an error when we detect that.

**Comment by mattersoflight** [comment]
> There is an API argument (TIFFConverter(chunks=...)) to pass in the exact chunk size to override this default behavior, possibly at the cost of conversion speed (when acquisition order is not CZYX). We can promote that to a CLI option if necessary.

This looks like a good solution to me @ziw-liu.
