### ISSUE TITLE
`iohub convert` would be more efficient if it reads whole XYZ volumes at a time

### ISSUE THREAD

**Issue by ieivanov** [czbiohub-sf/iohub#177]
Conversion to zarr is turning our to be one of the slower steps in our analysis pipelines.

Currently `iohub convert` reads and writes one image at a time using a call to `reader.get_image(P, T, C, Z)`. The conversion would be faster if we read and write whole XYZ volumes at a time using `reader.get_zarr(P)[T, C]`.

**Comment by ziw-liu** [comment]
The `get_zarr` method of the MM readers except NDTiffReader (which returns a Dask array instead of Zarr) will build the 5D zarr array `in memory` at initialization time, i.e. 'eager' instead of 'lazy'. Since the arrays can well be larger than memory, this is not really feasible. For fast ndtiff conversion, see [this (outdated) example](https://github.com/czbiohub-sf/compmicro-sandbox/blob/master/iohub_scripts/convert/convert_isim_fish.py). Also see https://github.com/czbiohub-sf/iohub/issues/176#issuecomment-1682687978.
